[versions]

kotlin = "2.2.20"
kotlinx-datetime = "0.7.1"
ktor = "3.3.0"
caupain = "1.4.1"
dokka = "2.0.0"

[libraries]

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

[plugins]

jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
caupain = { id = "com.deezer.caupain", version.ref = "caupain" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka"  }
